package jobs

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func prepareBuildConfigOverrides(repoPath string, baseEnvName string, jobID string, options BuildOptions) (string, string, error) {
	if options.IsEmpty() {
		return "", baseEnvName, nil
	}
	if err := ValidateDevice(baseEnvName); err != nil {
		return "", "", fmt.Errorf("invalid target environment %q: %w", baseEnvName, err)
	}

	overrideEnvName := buildOverrideEnvName(jobID)
	if err := ValidateDevice(overrideEnvName); err != nil {
		return "", "", fmt.Errorf("invalid override environment name %q: %w", overrideEnvName, err)
	}

	configAbsolutePath := filepath.Join(repoPath, "platformio.ini")

	content := renderBuildOverrideConfig(baseEnvName, overrideEnvName, options)
	file, err := os.OpenFile(configAbsolutePath, os.O_APPEND|os.O_WRONLY, 0)
	if err != nil {
		return "", "", fmt.Errorf("open platformio.ini for build overrides: %w", err)
	}
	defer file.Close()

	if _, err := file.WriteString(content); err != nil {
		return "", "", fmt.Errorf("append build override config: %w", err)
	}

	return "", overrideEnvName, nil
}

func buildOverrideEnvName(jobID string) string {
	trimmed := strings.TrimSpace(jobID)
	if trimmed == "" {
		return "mfb-custom"
	}

	builder := strings.Builder{}
	builder.Grow(len(trimmed) + 11)
	builder.WriteString("mfb-custom-")
	for _, char := range trimmed {
		switch {
		case char >= 'a' && char <= 'z':
			builder.WriteRune(char)
		case char >= 'A' && char <= 'Z':
			builder.WriteRune(char + 32)
		case char >= '0' && char <= '9':
			builder.WriteRune(char)
		default:
			builder.WriteRune('-')
		}
	}
	return builder.String()
}

func renderBuildOverrideConfig(baseEnvName string, overrideEnvName string, options BuildOptions) string {
	builder := strings.Builder{}
	builder.WriteString("\n; generated by meshtastic-firmware-builder\n")
	builder.WriteString("[env:")
	builder.WriteString(overrideEnvName)
	builder.WriteString("]\n")
	builder.WriteString("extends = env:")
	builder.WriteString(baseEnvName)
	builder.WriteString("\n")

	appendOverrideOption(&builder, "build_flags", baseEnvName, options.BuildFlags)
	appendOverrideOption(&builder, "lib_deps", baseEnvName, options.LibDeps)

	return builder.String()
}

func appendOverrideOption(builder *strings.Builder, optionName string, baseEnvName string, values []string) {
	if len(values) == 0 {
		return
	}

	builder.WriteString(optionName)
	builder.WriteString(" =\n")
	builder.WriteString("  ${env:")
	builder.WriteString(baseEnvName)
	builder.WriteString(".")
	builder.WriteString(optionName)
	builder.WriteString("}\n")
	for _, value := range values {
		builder.WriteString("  ")
		builder.WriteString(value)
		builder.WriteString("\n")
	}
}
